# Generated by Django 4.2.4 on 2023-10-23 06:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
