# Generated by Django 4.2.4 on 2023-10-23 07:02

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_blogmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
